<a href="https://colab.research.google.com/github/sc-mari-a/KSVD/blob/main/Doroshenko_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. Аналіз даних
  [Посилання на GitHub](https://github.com/sc-mari-a/KSVD)

1) Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np
vec = np.arange(1, 21)
vec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

2) Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [2]:
matrix = np.ones((4, 4), dtype=int)
matrix

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

3) Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [3]:
np.random.uniform(-1, 1, size=(5,5))

array([[-0.9529336 , -0.12892308, -0.78371031, -0.28269137,  0.28211933],
       [ 0.80016462,  0.31285142, -0.26058265, -0.49042758,  0.65921852],
       [-0.98474766,  0.69346303,  0.78761515, -0.46211003,  0.25159101],
       [ 0.33426986,  0.09987743,  0.73544497,  0.50255487,  0.8779605 ],
       [-0.08023418,  0.41221063,  0.85929532, -0.42179624, -0.3677197 ]])

4) Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
np.random.uniform(0, 1, size=(3,3))

array([[0.51707863, 0.78949956, 0.95144217],
       [0.55429241, 0.0308517 , 0.97312832],
       [0.06546446, 0.07823602, 0.83351862]])

5) Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [16]:
a = np.random.randint(1, 21, size=(1,6))
b = np.random.randint(1, 21, size=(1,6))

print(f"a = {a} \nb = {b}\n")
print(f"a + b = {a+b}")
print(f"a - b = {a-b}")
print(f"a * b = {a*b}")

a = [[13  8  9 18  9 18]] 
b = [[2 4 9 5 9 6]]

a + b = [[15 12 18 23 18 24]]
a - b = [[11  4  0 13  0 12]]
a * b = [[ 26  32  81  90  81 108]]


6) Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [39]:
a = np.random.randint(1, 6, size=(3,2))
b = np.random.randint(1, 6, size=(2,4))

print(f"{a}\n\n{b}\n")

print(f"a * b = \n{np.dot(a, b)}")

[[5 1]
 [5 5]
 [3 3]]

[[1 5 2 3]
 [1 5 4 1]]

a * b = 
[[ 6 30 14 16]
 [10 50 30 20]
 [ 6 30 18 12]]


7) Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [19]:
m = np.random.uniform(0, 1, size=(3,3))
print(m)
print()
print(m.T) #або m.transpose()

[[0.77511991 0.46278793 0.18770471]
 [0.57362064 0.60702967 0.4465959 ]
 [0.39937028 0.61109035 0.39349623]]

[[0.77511991 0.57362064 0.39937028]
 [0.46278793 0.60702967 0.61109035]
 [0.18770471 0.4465959  0.39349623]]


8) Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [40]:
a = np.random.randint(1, 11, size=(3,3))
b = np.random.randint(1, 11, size=(3,3))
a-b

array([[ 4, -3,  1],
       [-1, -4, -7],
       [ 3, -1, -8]])

9) Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [44]:
a = np.random.randint(-5, 5, size=(3,3))
b = np.random.randint(-5, 5, size=(3,3))
print(a)
print()
print(b)
np.dot(a, b)

[[ 4  1 -2]
 [ 4 -4  1]
 [ 1 -4 -5]]

[[ 1  3  3]
 [ 0  0  4]
 [ 3 -4  3]]


array([[ -2,  20,  10],
       [  7,   8,  -1],
       [-14,  23, -28]])

10) Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [50]:
m = np.random.uniform(-1, 1, size=(3,3))
print(m)
print()
m.sum(axis=0).reshape(3, 1)     # axis=1 - вказуємо, щоб сумувалось по рядках (якщо не вказати, то sum сумує всі елем.), reshape - змінюємо розмір вектора

[[ 0.26030775  0.38689567  0.94009603]
 [ 0.66658603  0.20738672 -0.97886641]
 [-0.72567     0.5789143   0.0385561 ]]



array([[ 2.01223782e-01],
       [ 1.17319669e+00],
       [-2.14287739e-04]])